name: PS5 (ps5-payload-dev)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ps5:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: |
        sudo apt update
        sudo apt install cmake pkg-config clang-15 lld-15
        sudo apt install build-essential autoconf libtool yasm nasm
        sudo apt install smpq gperf pkgconf libarchive-tools autopoint po4a git curl doxygen wget
        wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/download/v0.27/ps5-payload-dev.tar.gz
        sudo tar -xf ps5-payload-dev.tar.gz -C /

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: Packaging/ps5/build.sh

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-ps5.zip
        path: build-ps5/devilutionx-ps5.zip

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        asset_name: devilutionx-ps5.zip
        file: build-ps5/devilutionx-ps5.zip
        overwrite: true
